<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE LotteryDataResultsFeed [
<!ELEMENT LotteryDataResultsFeed (DrawDate)*>
<!ATTLIST LotteryDataResultsFeed Version CDATA #REQUIRED>
<!ELEMENT DrawDate (Country)*>
<!ATTLIST DrawDate date CDATA #REQUIRED>
<!ELEMENT Country (State | Game)+>
<!ATTLIST Country name CDATA #REQUIRED>
<!ELEMENT State (Game)+>
<!ATTLIST State name CDATA #REQUIRED>
<!ELEMENT Game (CurrencySymbol? , DaysPlayed? , NextDraw? , NumberString , NumberList , BonusList? , JackpotList?)>
<!ATTLIST Game name CDATA #REQUIRED>
<!ELEMENT CurrencySymbol (#PCDATA)>
<!ELEMENT NextDraw (#PCDATA)>
<!ELEMENT NumberString (#PCDATA)>
<!ELEMENT NumberList (Number)+>
<!ELEMENT Number (#PCDATA)>
<!ELEMENT BonusList (BonusNumber)+>
<!ELEMENT BonusNumber (#PCDATA)>
<!ELEMENT JackpotList (CurrentJackpot? , Jackpot? , PreviousJackpot? , USD_CurrentJackpot? , USD_PreviousJackpot?)>
<!ATTLIST JackpotList rollover (yes | no) #IMPLIED>
<!ELEMENT CurrentJackpot (#PCDATA)>
<!ELEMENT Jackpot (#PCDATA)>
<!ELEMENT PreviousJackpot (#PCDATA)>
<!ELEMENT USD_CurrentJackpot (#PCDATA)>
<!ELEMENT USD_PreviousJackpot (#PCDATA)>
<!ELEMENT DaysPlayed (Day)+>
<!ELEMENT Day (#PCDATA)>
]>
<LotteryDataResultsFeed Version="2.7">
    <DrawDate date="2012-08-28">
        <Country name="USA">
            <State name="2by2">
                <Game name="2by2">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 03:35:00 GMT</NextDraw>
                    <NumberString>Red: (16, 26), White: (4, 26)</NumberString>
                    <NumberList>
                        <Number>Red: (16</Number>
                        <Number>26)</Number>
                        <Number>White: (4</Number>
                        <Number>26)</Number>
                    </NumberList>
                </Game>
            </State>
            <State name="Arizona">
                <Game name="Pick 3">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>MON</Day>
                        <Day>TUE</Day>
                        <Day>WED</Day>
                        <Day>THU</Day>
                        <Day>FRI</Day>
                        <Day>SAT</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 04:30:00 GMT</NextDraw>
                    <NumberString>6, 4, 6</NumberString>
                    <NumberList>
                        <Number>6</Number>
                        <Number>4</Number>
                        <Number>6</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Fantasy 5">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>MON</Day>
                        <Day>TUE</Day>
                        <Day>WED</Day>
                        <Day>THU</Day>
                        <Day>FRI</Day>
                        <Day>SAT</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 05:00:00 GMT</NextDraw>
                    <NumberString>15, 24, 25, 29, 36</NumberString>
                    <NumberList>
                        <Number>15</Number>
                        <Number>24</Number>
                        <Number>25</Number>
                        <Number>29</Number>
                        <Number>36</Number>
                    </NumberList>
                    <JackpotList rollover="yes">
                        <CurrentJackpot>59000</CurrentJackpot>
                        <PreviousJackpot>90000</PreviousJackpot>
                    </JackpotList>
                </Game>
                <Game name="Cash 4">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>MON</Day>
                        <Day>TUE</Day>
                        <Day>WED</Day>
                        <Day>THU</Day>
                        <Day>FRI</Day>
                        <Day>SAT</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 04:30:00 GMT</NextDraw>
                    <NumberString>3, 18, 21, 26</NumberString>
                    <NumberList>
                        <Number>3</Number>
                        <Number>18</Number>
                        <Number>21</Number>
                        <Number>26</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="2by2">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>MON</Day>
                        <Day>TUE</Day>
                        <Day>WED</Day>
                        <Day>THU</Day>
                        <Day>FRI</Day>
                        <Day>SAT</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 04:35:00 GMT</NextDraw>
                    <NumberString>Red: (1, 21), White: (16, 19)</NumberString>
                    <NumberList>
                        <Number>Red: (1</Number>
                        <Number>21)</Number>
                        <Number>White: (16</Number>
                        <Number>19)</Number>
                    </NumberList>
                </Game>
            </State>
            <State name="Arkansas">
                <Game name="Natural State Jackpot ">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>MON</Day>
                        <Day>TUE</Day>
                        <Day>WED</Day>
                        <Day>THU</Day>
                        <Day>FRI</Day>
                        <Day>SAT</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 00:00:00 GMT</NextDraw>
                    <NumberString>2, 11, 31, 35, 37</NumberString>
                    <NumberList>
                        <Number>2</Number>
                        <Number>11</Number>
                        <Number>31</Number>
                        <Number>35</Number>
                        <Number>37</Number>
                    </NumberList>
                    <JackpotList rollover="yes">
                        <CurrentJackpot>35000</CurrentJackpot>
                        <PreviousJackpot>30000</PreviousJackpot>
                    </JackpotList>
                </Game>
                <Game name="Midday Cash 4">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>MON</Day>
                        <Day>TUE</Day>
                        <Day>WED</Day>
                        <Day>THU</Day>
                        <Day>FRI</Day>
                        <Day>SAT</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 00:00:00 GMT</NextDraw>
                    <NumberString>6, 7, 1, 5</NumberString>
                    <NumberList>
                        <Number>6</Number>
                        <Number>7</Number>
                        <Number>1</Number>
                        <Number>5</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Midday Cash 3">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>MON</Day>
                        <Day>TUE</Day>
                        <Day>WED</Day>
                        <Day>THU</Day>
                        <Day>FRI</Day>
                        <Day>SAT</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 00:00:00 GMT</NextDraw>
                    <NumberString>1, 8, 1</NumberString>
                    <NumberList>
                        <Number>1</Number>
                        <Number>8</Number>
                        <Number>1</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Cash 4">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 00:00:00 GMT</NextDraw>
                    <NumberString>0, 7, 1, 1</NumberString>
                    <NumberList>
                        <Number>0</Number>
                        <Number>7</Number>
                        <Number>1</Number>
                        <Number>1</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Cash 3">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 00:00:00 GMT</NextDraw>
                    <NumberString>0, 9, 8</NumberString>
                    <NumberList>
                        <Number>0</Number>
                        <Number>9</Number>
                        <Number>8</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
            </State>
            <State name="California">
                <Game name="Midday 3">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 20:00:00 GMT</NextDraw>
                    <NumberString>9, 4, 9</NumberString>
                    <NumberList>
                        <Number>9</Number>
                        <Number>4</Number>
                        <Number>9</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Fantasy 5">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 01:59:00 GMT</NextDraw>
                    <NumberString>1, 4, 14, 20, 26</NumberString>
                    <NumberList>
                        <Number>1</Number>
                        <Number>4</Number>
                        <Number>14</Number>
                        <Number>20</Number>
                        <Number>26</Number>
                    </NumberList>
                    <JackpotList rollover="yes">
                        <CurrentJackpot>59000</CurrentJackpot>
                        <PreviousJackpot>110000</PreviousJackpot>
                    </JackpotList>
                </Game>
                <Game name="Daily Derby">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 01:59:00 GMT</NextDraw>
                    <NumberString>1st: 12-Lucky Charms, 2nd: 1-Gold Rush, 3rd: 6-Whirl Win, Race Time: 1:44.91</NumberString>
                    <NumberList>
                        <Number>1st: 12-Lucky Charms</Number>
                        <Number>2nd: 1-Gold Rush</Number>
                        <Number>3rd: 6-Whirl Win</Number>
                        <Number>Race Time: 1:44.91</Number>
                    </NumberList>
                    <JackpotList rollover="yes">
                        <CurrentJackpot>261000</CurrentJackpot>
                        <PreviousJackpot>257000</PreviousJackpot>
                    </JackpotList>
                </Game>
                <Game name="Daily 4">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 01:59:00 GMT</NextDraw>
                    <NumberString>1, 8, 3, 1</NumberString>
                    <NumberList>
                        <Number>1</Number>
                        <Number>8</Number>
                        <Number>3</Number>
                        <Number>1</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Daily 3">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 01:59:00 GMT</NextDraw>
                    <NumberString>5, 5, 4</NumberString>
                    <NumberList>
                        <Number>5</Number>
                        <Number>5</Number>
                        <Number>4</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
            </State>
            <State name="Colorado">
                <Game name="Cash 5">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 01:35:00 GMT</NextDraw>
                    <NumberString>8, 22, 23, 29, 30</NumberString>
                    <NumberList>
                        <Number>8</Number>
                        <Number>22</Number>
                        <Number>23</Number>
                        <Number>29</Number>
                        <Number>30</Number>
                    </NumberList>
                    <JackpotList rollover="yes">
                        <CurrentJackpot>125000</CurrentJackpot>
                        <PreviousJackpot>20000</PreviousJackpot>
                    </JackpotList>
                </Game>
            </State>
            <State name="Connecticut">
                <Game name="Play 4">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 02:29:00 GMT</NextDraw>
                    <NumberString>4, 9, 8, 7</NumberString>
                    <NumberList>
                        <Number>4</Number>
                        <Number>9</Number>
                        <Number>8</Number>
                        <Number>7</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Play 3">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 02:29:00 GMT</NextDraw>
                    <NumberString>2, 0, 6</NumberString>
                    <NumberList>
                        <Number>2</Number>
                        <Number>0</Number>
                        <Number>6</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Midday 4">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 17:57:00 GMT</NextDraw>
                    <NumberString>1, 2, 6, 1</NumberString>
                    <NumberList>
                        <Number>1</Number>
                        <Number>2</Number>
                        <Number>6</Number>
                        <Number>1</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Midday 3">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 17:57:00 GMT</NextDraw>
                    <NumberString>8, 9, 9</NumberString>
                    <NumberList>
                        <Number>8</Number>
                        <Number>9</Number>
                        <Number>9</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Classic Lotto">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>TUE</Day>
                        <Day>FRI</Day>
                    </DaysPlayed>
                    <NextDraw>2012-09-01 02:38:00 GMT</NextDraw>
                    <NumberString>2, 3, 9, 11, 13, 42</NumberString>
                    <NumberList>
                        <Number>2</Number>
                        <Number>3</Number>
                        <Number>9</Number>
                        <Number>11</Number>
                        <Number>13</Number>
                        <Number>42</Number>
                    </NumberList>
                    <JackpotList rollover="yes">
                        <CurrentJackpot>2700000</CurrentJackpot>
                        <PreviousJackpot>2600000</PreviousJackpot>
                    </JackpotList>
                </Game>
                <Game name="Cash 5">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 02:29:00 GMT</NextDraw>
                    <NumberString>3, 5, 6, 14, 30</NumberString>
                    <NumberList>
                        <Number>3</Number>
                        <Number>5</Number>
                        <Number>6</Number>
                        <Number>14</Number>
                        <Number>30</Number>
                    </NumberList>
                    <JackpotList rollover="yes">
                        <CurrentJackpot>125000</CurrentJackpot>
                        <PreviousJackpot>100000</PreviousJackpot>
                    </JackpotList>
                </Game>
            </State>
            <State name="Delaware">
                <Game name="Play 4 Midday">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>MON</Day>
                        <Day>TUE</Day>
                        <Day>WED</Day>
                        <Day>THU</Day>
                        <Day>FRI</Day>
                        <Day>SAT</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 17:58:00 GMT</NextDraw>
                    <NumberString>0, 7, 0, 8</NumberString>
                    <NumberList>
                        <Number>0</Number>
                        <Number>7</Number>
                        <Number>0</Number>
                        <Number>8</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Play 4">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 23:57:00 GMT</NextDraw>
                    <NumberString>8, 5, 5, 7</NumberString>
                    <NumberList>
                        <Number>8</Number>
                        <Number>5</Number>
                        <Number>5</Number>
                        <Number>7</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Play 3 Midday">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>MON</Day>
                        <Day>TUE</Day>
                        <Day>WED</Day>
                        <Day>THU</Day>
                        <Day>FRI</Day>
                        <Day>SAT</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 17:58:00 GMT</NextDraw>
                    <NumberString>1, 4, 3</NumberString>
                    <NumberList>
                        <Number>1</Number>
                        <Number>4</Number>
                        <Number>3</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Play 3">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 23:57:00 GMT</NextDraw>
                    <NumberString>7, 9, 2</NumberString>
                    <NumberList>
                        <Number>7</Number>
                        <Number>9</Number>
                        <Number>2</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Cash 5">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>TUE</Day>
                        <Day>SAT</Day>
                    </DaysPlayed>
                    <NextDraw>2012-09-01 23:57:00 GMT</NextDraw>
                    <NumberString>2, 5, 11, 20, 22, Doubler: 6</NumberString>
                    <NumberList>
                        <Number>2</Number>
                        <Number>5</Number>
                        <Number>11</Number>
                        <Number>20</Number>
                        <Number>22</Number>
                        <Number>Doubler: 6</Number>
                    </NumberList>
                    <JackpotList rollover="yes">
                        <CurrentJackpot>125000</CurrentJackpot>
                        <PreviousJackpot>28000</PreviousJackpot>
                    </JackpotList>
                </Game>
            </State>
            <State name="District of Columbia">
                <Game name="Midday DC5">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 18:14:00 GMT</NextDraw>
                    <NumberString>0, 0, 0, 6, 0</NumberString>
                    <NumberList>
                        <Number>0</Number>
                        <Number>0</Number>
                        <Number>0</Number>
                        <Number>6</Number>
                        <Number>0</Number>
                    </NumberList>
                </Game>
                <Game name="DC Lucky Numbers">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 00:15:00 GMT</NextDraw>
                    <NumberString>9, 0, 9</NumberString>
                    <NumberList>
                        <Number>9</Number>
                        <Number>0</Number>
                        <Number>9</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="DC Lucky Midday">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 18:14:00 GMT</NextDraw>
                    <NumberString>6, 7, 6</NumberString>
                    <NumberList>
                        <Number>6</Number>
                        <Number>7</Number>
                        <Number>6</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="DC 5">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 00:15:00 GMT</NextDraw>
                    <NumberString>1, 7, 7, 2, 7</NumberString>
                    <NumberList>
                        <Number>1</Number>
                        <Number>7</Number>
                        <Number>7</Number>
                        <Number>2</Number>
                        <Number>7</Number>
                    </NumberList>
                </Game>
                <Game name="DC 4 Midday">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 18:14:00 GMT</NextDraw>
                    <NumberString>4, 3, 3, 6</NumberString>
                    <NumberList>
                        <Number>4</Number>
                        <Number>3</Number>
                        <Number>3</Number>
                        <Number>6</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="DC 4">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-30 00:15:00 GMT</NextDraw>
                    <NumberString>2, 5, 8, 9</NumberString>
                    <NumberList>
                        <Number>2</Number>
                        <Number>5</Number>
                        <Number>8</Number>
                        <Number>9</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
            </State>
            <State name="Florida">
                <Game name="Play 4 Midday">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 17:20:00 GMT</NextDraw>
                    <NumberString>3, 2, 9, 2</NumberString>
                    <NumberList>
                        <Number>3</Number>
                        <Number>2</Number>
                        <Number>9</Number>
                        <Number>2</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Play 4">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 23:57:00 GMT</NextDraw>
                    <NumberString>8, 5, 8, 0</NumberString>
                    <NumberList>
                        <Number>8</Number>
                        <Number>5</Number>
                        <Number>8</Number>
                        <Number>0</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>5000</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Midday Cash 3">
                    <CurrencySymbol>$</CurrencySymbol>
                    <DaysPlayed>
                        <Day>ALL</Day>
                    </DaysPlayed>
                    <NextDraw>2012-08-29 17:20:00 GMT</NextDraw>
                    <NumberString>4, 1, 5</NumberString>
                    <NumberList>
                        <Number>4</Number>
                        <Number>1</Number>
                        <Number>5</Number>
                    </NumberList>
                    <JackpotList rollover="no">
                        <Jackpot>500</Jackpot>
                    </JackpotList>
                </Game>
                <Game name="Mega Money">